name: new_try
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png

